### ISSUE TITLE
Old unsynced data can override newer data

### ISSUE THREAD

**Issue by mr-nati** [dynamiclogic/tams-sql#1]
If an asset is modified on a device but it doesn't sync for a long time, when it is finally synced with the server (say, 10 years later), it could override all the modifications that have happened since the asset had been recorded. So instead of writing the last synced data to the DB we should write the last modified data.

**Comment by mr-nati** [comment]
Doesn't look like we're going to get around to this

**Comment by acbueff** [comment]
You open that right back up. I'm getting to
it....eventually...someday...maybe....naaah

**Comment by arashparnia** [comment]
His job at google must be too demanding 🤣

**Comment by javierationmex** [comment]
Come on man, I was just finishing up the fix for this
